#if !canImport(ObjectiveC)
import XCTest

extension FixturesTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FixturesTests = [
        ("testFixtures", testFixtures),
    ]
}

extension GeneratorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GeneratorTests = [
        ("testGenerator", testGenerator),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(FixturesTests.__allTests__FixturesTests),
        testCase(GeneratorTests.__allTests__GeneratorTests),
    ]
}
#endif
