//
// APIError.swift
//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import JSONUtilities

public enum APIError: Error {
    case unexpectedStatusCode(statusCode: Int, data: Data)
    case jsonDeserializationError(JSONUtilsError)
    case decodingError(DecodingError)
    case invalidBaseURL(String)
    case authorizationError(AuthorizationError)
    case networkError(Error)
    case unknownError(Error)
}
