//
// APIResponse.swift
//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

public typealias ResponseDecoder<T> = (Int, Any) throws -> T

protocol APIResponse {

  init(statusCode: Int, json: Any) throws
}
