//
// {{ enumName }}.swift
//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

{% if description %}
/** {{ description }} */
{% endif %}
public enum {{ enumName }}: String{% if raw.enumEmoji %}, EmojiConvertible{% endif %} {
    {% for enumCase in enums %}
    case {{ enumCase.name }} = "{{enumCase.value}}"
    {% endfor %}

    public static let cases: [{{ enumName }}] = [
      {% for enumCase in enums %}
      .{{ enumCase.name }},
      {% endfor %}
    ]
    {% if raw.enumEmoji %}

    public var emoji: String {
      switch self {
      {% for type,emoji in raw.enumEmoji %}
      case .{{ type | lowerCamelCase}}: return "{{ emoji }}"
      {% endfor %}
      {% if raw.enumEmoji.count != enums.count %}
      default: return ""
      {% endif %}
      }
    }
    {% endif %}
}
