//
// {{ enumName }}.swift
//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

{% if description %}
/** {{ description }}  */
{% endif %}
public enum {{ enumName }}: String {
    {% for enumCase in enums %}
    case {{ enumCase.name }} = "{{enumCase.value}}"
    {% endfor %}
}
